### ISSUE TITLE
I would like to get instructions on what parameters need changing (account settings) to run the white label api from github

### ISSUE THREAD

**Issue by lsdace30095** [softlayer/stratos#2]
(Srastos_masrer)? Do we need to change the gem file parameters? We attempted to run the github download on IBM Bluemix using Rubyand encounter this error (
FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase)

**Comment by lsdace30095** [comment]
When attempting to run from web hosting we get this:
Ruby on Rails
Start a Ruby Application

The system could not start the Ruby on Rails application.

NOTE: Gem::SourceIndex.from_installed_gems is deprecated with no replacement. It will be removed on or after 2011-10-01. Gem::SourceIndex.from_installed_gems called from /usr/lib/ruby/gems/1.8/gems/gem_plugin-0.2.3/lib/gem_plugin.rb:109. NOTE: from_installed_gems(arg) is deprecated. From /usr/lib/ruby/site_ruby/1.8/rubygems/deprecate.rb:63:in `send' NOTE: Gem::SourceIndex.from_gems_in is deprecated with no replacement. It will be removed on or after 2011-10-01. Gem::SourceIndex.from_gems_in

**Comment by fernandes** [comment]
Hi @lsdace30095 we are currently under development as you can check under https://github.com/softlayer/stratos/issues/1

I've been working on stratos and a new client for SoftLayer, so you can expect something new next month.

Thank you
