### ISSUE TITLE
Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`

### ISSUE THREAD

**Issue by lsdace30095** [softlayer/stratos#4]
We have created the secrets.yml file in config folder and formatted it as
api_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
username = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
endpoint_url = https://api.softlayer.com/xmlrpc/v3/
timeout = 60

However I continue o get error in browser Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`.  

How and where should this file be formatted and located?

**Comment by fernandes** [comment]
Hi Lou,

Actually this is almost a blank rails repo, just the skeleton to keep the development forward. I proposed some dev guidelines here: https://github.com/softlayer/stratos/issues/1 but we haven't moved yet.

To address the `secrets.yml` file you said I made this [commit](https://github.com/softlayer/stratos/commit/6fea9cdbcd7b2dbb652e080cd8f73a27c4b2291d), you just need to set the `SECRET_KEY_BASE` environment variable. (you can generate with `rake secret`)

Thank you

**Comment by fernandes** [comment]
@lsdace30095 just following up this issue and #2 , now we have a usable version on master if you'd like to try, now you should get it working without (I hope so heheh) any issue.
